application: myapp-nn899
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.application
- url: /questions
  script: main.application
- url: /questions/.*
  script: main.application

libraries:
- name: django
  version: "1.5"
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
